# Generated by Django 2.0.6 on 2019-05-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
